### ISSUE TITLE
Calling Method on chart element

### ISSUE THREAD

**Issue by Gervwyk** [amcharts/amcharts3-react#13]
Hi. 
Is there a way to evoke a method on a chart. Such as:
`chart.zoomOut()`

I'm struggling to find a handle for the chart object. 
To render the chart i use:

  `<AmCharts ref={chart_${this.props.tileid}} {...this.chart} dataProvider={this.props.data} />`

I tried to inspect the element to see if I can access these methods through:
`ch = this.refs[chart_${this.props.tileid}]`

However in the 'ch' object I can not seem to find any of the methods mentioned in:
https://docs.amcharts.com/3/javascriptcharts/AmSerialChart#zoomOut

How would one reference a element to evoke a method on it?

**Comment by Pauan** [comment]
Hi @Gervwyk,

I'm not sure if this will work, but try this:

```
ch.state.chart.zoomOut();
```

Also, if you use an [event listener](https://docs.amcharts.com/3/javascriptcharts/AmSerialChart#listeners), you can access the chart:

```
React.createElement(AmCharts.React, {
  listeners: [{
    event: "init",
    method: function (event) {
      console.log(event.chart);
    }
  }]
});
```

**Comment by Gervwyk** [comment]
Thanks. This solved my problem. I am able to call:
ch.state.chart.zoomOut();

**Comment by Pauan** [comment]
Great! I'm glad it works.

**Comment by EmirGluhbegovic** [comment]
Hey, How can I know when the amChart component is ready? 
I tried calling this.refs.chart.state but it return chart property as null.
If I console.log() this.refs.chart then I get back a chart instance b.

I did this in componentDidMount(). Any suggestions thanks

**Comment by EmirGluhbegovic** [comment]
Trying to convert the image to base64
