### ISSUE TITLE
Can not install trough package.json webpack

### ISSUE THREAD

**Issue by Darnok11** [amcharts/amcharts3-react#25]
I'm trying to install amcharts3 through package.json in react application created by 
[https://github.com/facebookincubator/create-react-app](url)

`{
  "name": "test2",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "react-scripts": "0.8.4",
    "amcharts3": "amcharts/amcharts3",
    "amcharts3-react": "amcharts/amcharts3-react"
  },
  "dependencies": {
    "react": "^15.4.1",
    "react-dom": "^15.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}`

After npm install I get error:  
`npm ERR! git submodule -q update --init --recursive: git: 'submodule' is not a git command. See 'git --help'.
npm ERR! git submodule -q update --init --recursive: 
npm ERR! git submodule -q update --init --recursive: git: 'submodule' is not a git command. See 'git --help'.
npm ERR! git submodule -q update --init --recursive: 
The authenticity of host 'github.com (192.30.253.113)' can't be established.
[...]`
(my node v6.4.0 and npm  v3.10.3)

**Comment by Pauan** [comment]
@Darnok11 What is your Git version (`git --version`)?

**Comment by Darnok11** [comment]
My git version - 2.5.5
I do not exactly know what was the problem but I have reinstalled my application and after added dependencies installation proceeded successful.

**Comment by Pauan** [comment]
@Darnok11 That's a pretty old version of git, you might want to consider upgrading.

In any case, I'm glad you were able to get it working.
