### ISSUE TITLE
page scroller

### ISSUE THREAD

**Issue by RahavLussato** [amcharts/amcharts3-react#27]
in my case i have couple of serial charts on the same div.
when i'm hover on one of the charts its always scroll to the first one.

how i can disable scroll on hover ?

**Comment by RahavLussato** [comment]
#28

**Comment by Pauan** [comment]
@RahavLussato Is this still an issue after #28 was fixed?

**Comment by RahavLussato** [comment]
@Pauan no, we can close this.
