### ISSUE TITLE
The event listener for the chart is not working.

### ISSUE THREAD

**Issue by kinszhang** [amcharts/amcharts3-react#33]
I tried add listener to the graph but it won't work, could you please if there anything wrong in my code or issue in the plugin? Thanks

<AmChart
            config={config}
            listeners={[
                {
                    "event": "clickGraphItem",
                    "method": (e)=>{console.debug(e,33333333)}
                },
                {
                    "event":"dataUpdated",
                    "method": (e)=>{console.debug(e,444444)}
                }
            ]}
        />

My config is 

const config = {
    "type": "serial",
    "categoryField": "date",
    "startDuration": 1,
    "autoMarginOffset": 20,
    "fontSize": 13,
    "colors": [
        "#caadfa",
        "#afe2f3"
    ],
    "categoryAxis": {
        "startOnAxis": true,
        "autoWrap": true,
        "offset" : 10,
        "gridThickness": 0,
        "axisThickness": 0
    },
    "graphs": [
        {
            "balloonText": "[[date]]:[[value]]",
            "fillColors": "#caadfa",
            "fillAlphas": 0.6,
            "lineAlpha": 0.4,
            "lineThickness" : 0,
            "markerType": "circle",
            "title": "Non-Identifiable",
            "valueField": "non-Identifiable"
        },
        {
            "balloonText": "[[date]]:[[value]]",
            "fillColors": "#afe2f3",
            "fillAlphas": 0.6,
            "lineAlpha": 0.4,
            "lineThickness" : 0,
            "markerType": "circle",
            "title": "Identifiable",
            "valueField": "identifiable"
        }
    ],
    "valueAxes": [
        {
            "stackType": "regular",
            "gridThickness": 0,
            "axisThickness": 0,
            "offset": 20
        }
    ],
    "legend": {
        "autoMargins": false,
        "equalWidths": true,
        "position": "absolute",
        "right": 10,
        "top": 0,
        "align" : "right",
        "valueText": ""
    },
    "balloon": {},
    "chartCursor": {
       "enabled": true,
       "animationDuration": 0,
       "categoryBalloonEnabled": false,
       "oneBalloonOnly": true,
       "cursorAlpha": 0,
       "balloonPointerOrientation": "vertical",
       "oneBalloonOnly": true,
       "selectWithoutZooming": true,
       "fullWidth": false,
       "graphBulletSize": 5,
       "leaveCursor": false,
       "tabIndex": 1,
       "zoomable": false
     },
    "dataProvider": [],
    "listeners" : []
};

**Comment by kinszhang** [comment]
I just figure out the proper way to inject the listeners into the chart, so issue resolved.

**Comment by L0516712** [comment]
How do u solve this problem  ?

**Comment by peebles** [comment]
Yeah, can you clue the rest of us in?  I see no doc on how to do this for react components.

**Comment by peebles** [comment]
Ok.  In other places in this wiki, it is clearly suggested that listeners is a prop on the chart component, but that DOES NOT WORK.  In other places, it is suggested that listeners is part of the config structure, and THIS DOES WORK.
