### ISSUE TITLE
Make clear this package provides AmMap

### ISSUE THREAD

**Issue by iddan** [amcharts/amcharts3-react#34]
As AmMap is a different module and the name suggests it's only for charts.

**Comment by Pauan** [comment]
@iddan I'm not sure what you're suggesting. This plugin does not provide AmMap. But it's probably possible to use AmMap by importing it with `require("ammap3/ammap/ammap.js")`

**Comment by iddan** [comment]
So it should be highlighted. Initially as a first time user of AmCharts and AmMap I was sure there are no React bindings to AmMap at all.
