### ISSUE TITLE
Should probably replace "devDependencies" in README.md

### ISSUE THREAD

**Issue by apendua** [amcharts/amcharts3-react#47]
This is alright for development environment,
```javascript
{
  "devDependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "@amcharts/amcharts3-react": "^2.0.0"
  }
}
```
but ideally these should be `dependencies` as that's the place where most people expect to find packages that get bundled in the production version. Of course, in most cases it does not break anything, but I think it's still forth fixing to reduce confusion.

**Comment by Pauan** [comment]
@apendua I think it's the opposite: bundled dependencies should use `devDependencies`

If you have a library which uses `dependencies`, then anybody using that library will download those dependencies even though they're not used.

However, the `script` example doesn't do any bundling, so you're right that it should be using `dependencies`

**Comment by Pauan** [comment]
The `script` example has been updated to use `dependencies`
