### ISSUE TITLE
SVG height exceeds containing div

### ISSUE THREAD

**Issue by nlokare** [amcharts/amcharts3-react#5]
Hi,

I am having two separate issues and a solution for either one would be greatly appreciated. 

I am trying to add a chart within a widget using [react-grid-layout](https://github.com/STRML/react-grid-layout#features). Whenever header text is added to my widget, within a div, the rendered AmCharts SVG hangs off the edge of the parent container div. I've tried a bunch of configurations but can't seem to figure out how to fix this. In my most recent attempt I've set the `config.height` property to "100%" but am still having issues.

My second solution was to call the component within a div, but when doing so the resulting chart does not show up. I have some code pasted below and some screenshots of what I am seeing. Any help would be greatly appreciated. I haven't seen this issue anywhere else on StackOverflow.

```
var LineGraph = React.createClass({
  render: function () {
    var config = require("../chart-configs/line-graph.js");
    config["dataProvider"] = this.props.dataProvider;
    return React.createElement(AmCharts, config);
  }
});
```

The LineGraph component is being used like so:
```
render: function () {
        return (
            <ReactGridLayout className="layout" layout={this.state.layout} cols={12} rowHeight={30} onLayoutChange={this.onLayoutChange} draggableHandle='.drag'>
                <div key={'a'} data-grid={{draggableHandle: 'drag'}}>
                    <div className="panel panel-default">
                        <div className="panel-heading drag">
                            <h3 className="panel-title">Impressions</h3>
                        </div>
                    </div>
                    <LineGraph dataProvider={this.state.dataProvider}/>
                </div>
                <div key={"b"} data-grid={{draggableHandle: 'drag'}}>
                     <div>Header</div>
                    <LineGraph dataProvider={this.state.dataProvider}/>
                </div>
            </ReactGridLayout>
        )
    }
```

For widget "a"
![image](https://cloud.githubusercontent.com/assets/5903288/18486501/2801296e-79a6-11e6-91c9-02b820d42123.png)

For widget "b"
![image](https://cloud.githubusercontent.com/assets/5903288/18486527/4350a94c-79a6-11e6-9367-53fc121435f0.png)

**Comment by martynasma** [comment]
Hi there,

Since you closed the issue, we're going to assume you have it resolved.

Feel free to contact us if you should have any further issues.

**Comment by yashshah** [comment]
@nlokare I'm facing the same issue, I will truly appreciate if you can update the issue with the solution you used to fix it. Thanks.

**Comment by nlokare** [comment]
@yashshah I did something like this:

```
<div class="chart-container">
    <LineGraph .../>
</div>
```

with CSS styling like 
```
.class-container {
  height: 80%;
}
```
