### ISSUE TITLE
Charts are not rendered using create-react-app version v1.0.7

### ISSUE THREAD

**Issue by Siaver** [amcharts/amcharts3-react#50]

**Comment by cmeiller** [comment]
Same here, have you solved your problem?

**Comment by Siaver** [comment]
Yes, I set the height of the 'div' wrapper for the AmCharts.React component to '400px'.

**Comment by cmeiller** [comment]
@Siaver Thanks!

**Comment by doguhanokumus** [comment]
Thanks to @Siaver, his answer solves my issue too.
Check #52

**Comment by Pauan** [comment]
I'm glad you were able to solve the problem, I'm going to close this now.
