### ISSUE TITLE
publish v3 to npm

### ISSUE THREAD

**Issue by DimaRGB** [amcharts/amcharts3-react#55]
`npm i @amcharts/amcharts3-react@^3` doesn't work.

The last version is 2.0.8 in [npm](https://www.npmjs.com/package/@amcharts/amcharts3-react)

**Comment by Pauan** [comment]
We had already published `3.0.0` to npm, but it seems there was a bug in npm that caused it to not show up. We have republished it, so it should work now. Thanks for letting us know about this.

**Comment by DimaRGB** [comment]
It's ok now, 3.0.1.

Why do you not create tags and release notes ?

**Comment by Pauan** [comment]
I guess we could add tags to GitHub, what is the benefit of doing that?

We already have release notes, at the bottom of the README.

**Comment by DimaRGB** [comment]
one of them: check code for old version.
