### ISSUE TITLE
Is there a way to get this working without <script> tag?

### ISSUE THREAD

**Issue by RaedsLab** [amcharts/amcharts3-react#66]
Hello I'm using the create-react-app boilerplate with WebPack 

Is there a way to import AmCharts in a React Component without having to use <script> tags ?

**Comment by Pauan** [comment]
@RaedsLab AmCharts v3 will only work with `<script>` tags. [Here](https://github.com/amcharts/amcharts3-react/issues/41#issuecomment-293155215) is a more in-depth explanation of why.

AmCharts v4 will fully support npm and webpack, but it's not released yet.

**Comment by RaedsLab** [comment]
Is there a roadmap on AmCharts v4 ?

**Comment by martynasma** [comment]
Let me jump in. It's currently under development. Expect a beta early in 2018.
