### ISSUE TITLE
Examples directory too big

### ISSUE THREAD

**Issue by davidegurgone** [amcharts/amcharts3-react#69]
Hi,
The big amounts of very small files in node_modules/@amcharts/amcharts3-react directory, produces an issue on some Windows / NTFS Environments that makes impossible to work.

In our team we moved the library and installed as a local path and removed the examples directory and now it is working fine.

Probably it's enough to remove the library from the npm package, or there is something I'm missing?

D.

**Comment by Pauan** [comment]
Hm, that's very odd, the `node_modules` folder shouldn't be published to npm, I'll look into it.

**Comment by Pauan** [comment]
This has been fixed, please upgrade to version `3.0.4`. Thanks for pointing this out!
