### ISSUE TITLE
Libraries not found (404 error)

### ISSUE THREAD

**Issue by yamilelias** [amcharts/amcharts3-react#75]
Following the [column chart image example](https://www.amcharts.com/demos/column-chart-images-top/) in the documentation, I tried to make it works in a React project. I have included the AmCharts through `npm install` and then imported it to file.

```
import React from 'react';
import 'amcharts3';
import 'amcharts3/amcharts/serial';
import 'amcharts3/amcharts/themes/light';
import 'amcharts3/amcharts/plugins/export/export.min';
import 'amcharts3/amcharts/plugins/export/export.css';
import AmCharts from '@amcharts/amcharts3-react';
```
The problem is that it seems that the other libraries aren't found:

![image](https://user-images.githubusercontent.com/9338305/39670017-0b6411be-50b8-11e8-8bd6-3d2865e55d44.png)

Importing them to try to solve the problem didn't worked:

```
import 'amcharts3/amcharts/plugins/export/libs/fabric.js/fabric.min';
import 'amcharts3/amcharts/plugins/export/libs/FileSaver.js/FileSaver.min';
import 'amcharts3/amcharts/plugins/export/libs/jszip/jszip.min';
import 'amcharts3/amcharts/plugins/export/libs/pdfmake/pdfmake.min';
```

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **33972**.
> (replying here will automatically notify amCharts support agent)

Hi there,

Noted. I'll work with the team to add the reasons but the readme instructions do specifically state to use script tags to load the AmCharts libraries in step 2.

Best,

Anthony Piris
amCharts

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **33972**.
> (replying here will automatically notify amCharts support agent)

Correction - step 3, not step 2.

Also note that the examples also use script tags.
