### ISSUE TITLE
color changin

### ISSUE THREAD

**Issue by johnd3v** [amcharts/amcharts3-react#84]
how do i change dynamically the color of pie chart and stock charts?

**Comment by martynasma** [comment]
I'm sorry, you'll have to be more specific than that. What are you trying to achieve?

**Comment by milonite** [comment]
I have the same problem, in the docs you can find https://www.amcharts.com/docs/v3/tutorials/individually-setting-color-pie-chart-slices/

But dosnt work in amcharts3-react
