### ISSUE TITLE
Support for react v17.x in peerDependencies

### ISSUE THREAD

**Issue by MarioSimou** [amcharts/amcharts3-react#96]
Hey. My team and I we are using @amcharts/amcharts3-react and I was wondering if we could add support for react v17.x. Essentially, we need to update the package.json and peerDependencies section to include react v17x. Sicne npm v7, the installation fails from our side because v17 is not allowed in the peerDependencies.

I can raise a PR with the necessary change

**Comment by Pauan** [comment]
Sorry for the delay on this, all of our development effort goes toward V5, since V3 is quite old and is no longer supported.

Version 3.1.1 now has support for React 17 and React 18.
